### PR TITLE
Template localization for MUI compatibility

### PR DESCRIPTION
**Pull request by PooLP**
Hi,
Little update to add a localization system in HB template for MUI compatibility and update to 1.4.1 SharePoint framework.
Bye.

### CODE REVIEW

**Comment by estruyf** [comment]
Great to see how you approached it, I had something similar in place. Will process the PR later this week. Thanks!

**Comment by PooLP** [comment]
Hi, Sorry for response delay, I was on holiday ... thanks, but, I do not know if it's the best way.

Question : 
The automatic import of ui-fabric core affect a default ui-fabric class for use a dynamic theme color. it's a problem if i add a option for desactived this import ?

Thanks

**Comment by estruyf** [comment]
I merged your and my approach into the DEV branch. Major differences are that I moved the translations to the metadata section + changed the object a bit so that every resource is its own object. Each resource value can also have a default value, so that allows you to fallback if another language is not provided.

**Comment by PooLP** [comment]
Thanks for the merge.

For my another problem, I opened new issue : https://github.com/estruyf/react-handlebars-search/issues/16.

**Comment by estruyf** [comment]
Closed this one as the one to the DEV branch has just been merged.

**Pull request closed without merging**
